#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //新增 agent 表
* @File: 14cda82e98a4_新增_agent_表.py
* @Time: 2026/09/19 23:04:19
* @All Rights Reserve By Brtc
'''
"""新增 agent 表

Revision ID: 14cda82e98a4
Revises: 355dde80e295
Create Date: 2026-09-19 23:04:19.788754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14cda82e98a4'
down_revision = '355dde80e295'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，创建 agent 表
    * @Date :2026/09/19 23:04:19
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('peer_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('agent_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_agent_id')
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.create_index('agent_account_id_idx', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 agent 表
    * @Date :2026/09/19 23:04:19
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_index('agent_account_id_idx')

    op.drop_table('agent')
    # ### end Alembic commands ###
