#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //新增 agent.gateway_url
* @File: 162008c3bd67_新增_agent_gateway_url.py
* @Time: 2026/09/20 09:05:28
* @All Rights Reserve By Brtc
'''
"""新增 agent.gateway_url

Revision ID: 162008c3bd67
Revises: 8a8385b82551
Create Date: 2026-09-20 09:05:28.175925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162008c3bd67'
down_revision = '8a8385b82551'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，为 agent 表新增 gateway_url
    * @Date :2026/09/20 09:05:28
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_url', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 agent.gateway_url
    * @Date :2026/09/20 09:05:28
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('gateway_url')

    # ### end Alembic commands ###
