#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //新增 server 表
* @File: 306fd0e6f4e4_新增_server_表.py
* @Time: 2026/09/23 22:06:33
* @All Rights Reserve By Brtc
'''
"""新增 server 表

Revision ID: 306fd0e6f4e4
Revises: e6a19c4d8b20
Create Date: 2026-09-23 22:06:33.573348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '306fd0e6f4e4'
down_revision = 'e6a19c4d8b20'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，创建 server 表
    * @Date :2026/09/23 22:06:33
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_server_id')
    )
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.create_index('server_account_id_idx', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 server 表
    * @Date :2026/09/23 22:06:33
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_index('server_account_id_idx')

    op.drop_table('server')
    # ### end Alembic commands ###
