#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //account 与 upload_file 的初始数据库迁移
* @File: 355dde80e295_初始化_account_与_upload_file.py
* @Time: 2026/09/19 16:21:15
* @All Rights Reserve By Brtc
'''
"""初始化 account 与 upload_file

Revision ID: 355dde80e295
Revises: 
Create Date: 2026-09-19 16:21:15.764490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355dde80e295'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，创建 account、account_oauth、upload_file 表
    * @Date :2026/09/19 16:21:15
    * @Param:
    无
    * @return：无
    """
    # uuid_generate_v4() 依赖 uuid-ossp 扩展
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('email', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('avatar', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('password', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True),
    sa.Column('password_salt', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True),
    sa.Column('assistant_agent_conversation_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('last_login_ip', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_account_id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index('account_email_idx', ['email'], unique=False)

    op.create_table('account_oauth',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('openid', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('encrypted_token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_account_oauth_id')
    )
    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.create_index('account_oauth_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('account_oauth_openid_provider_idx', ['openid', 'provider'], unique=False)

    op.create_table('upload_file',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('key', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('extension', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('mime_type', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('hash', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_upload_file_id')
    )
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.create_index('upload_file_account_id_idx', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 account、account_oauth、upload_file 表
    * @Date :2026/09/19 16:21:15
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.drop_index('upload_file_account_id_idx')

    op.drop_table('upload_file')
    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.drop_index('account_oauth_openid_provider_idx')
        batch_op.drop_index('account_oauth_account_id_idx')

    op.drop_table('account_oauth')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index('account_email_idx')

    op.drop_table('account')
    # ### end Alembic commands ###
