#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //调整 conversation 字段
* @File: 3c5834073468_调整_conversation_字段.py
* @Time: 2026/09/20 23:22:20
* @All Rights Reserve By Brtc
'''
"""调整 conversation 字段

Revision ID: 3c5834073468
Revises: 81f29f4f4224
Create Date: 2026-09-20 23:22:20.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5834073468'
down_revision = '81f29f4f4224'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，删除 conversation.type、conversation.summary，新增 conversation.pinned
    * @Date :2026/09/20 23:22:20
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('summary')
        batch_op.add_column(sa.Column('pinned', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 conversation.pinned，恢复 conversation.type、conversation.summary
    * @Date :2026/09/20 23:22:20
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('pinned')
        batch_op.add_column(sa.Column('type', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###
