#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //新增 conversation 表
* @File: 81f29f4f4224_新增_conversation_表.py
* @Time: 2026/09/20 10:58:11
* @All Rights Reserve By Brtc
'''
"""新增 conversation 表

Revision ID: 81f29f4f4224
Revises: 162008c3bd67
Create Date: 2026-09-20 10:58:11.665874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81f29f4f4224'
down_revision = '162008c3bd67'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，创建 conversation 表
    * @Date :2026/09/20 10:58:11
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('peer_id', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('type', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('title', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_token_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_preview', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('conversation_info', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_conversation_id'),
    sa.UniqueConstraint('account_id', 'thread_id', name='uk_conversation_account_thread')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index('conversation_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('conversation_agent_id_idx', ['agent_id'], unique=False)
        batch_op.create_index('conversation_last_message_at_idx', ['last_message_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 conversation 表
    * @Date :2026/09/20 10:58:11
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index('conversation_last_message_at_idx')
        batch_op.drop_index('conversation_agent_id_idx')
        batch_op.drop_index('conversation_account_id_idx')

    op.drop_table('conversation')
    # ### end Alembic commands ###
