#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //补充 agent 字段与约束
* @File: 8a8385b82551_补充_agent_字段与约束.py
* @Time: 2026/09/19 23:15:33
* @All Rights Reserve By Brtc
'''
"""补充 agent 字段与约束

Revision ID: 8a8385b82551
Revises: 14cda82e98a4
Create Date: 2026-09-19 23:15:33.878605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a8385b82551'
down_revision = '14cda82e98a4'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，补充 agent 字段、唯一约束与索引
    * @Date :2026/09/19 23:15:33
    * @Param:
    无
    * @return：无
    """
    # 已有空值先补成空对象，否则 agent_info 无法改为非空
    op.execute("UPDATE agent SET agent_info = '{}'::jsonb WHERE agent_info IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('conversation_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('total_token_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('agent_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               server_default=sa.text("'{}'::jsonb"))
        batch_op.create_index('agent_peer_id_idx', ['peer_id'], unique=False)
        batch_op.create_unique_constraint('uk_agent_agent_id', ['agent_id'])

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，移除 agent 新增字段、唯一约束与索引
    * @Date :2026/09/19 23:15:33
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_constraint('uk_agent_agent_id', type_='unique')
        batch_op.drop_index('agent_peer_id_idx')
        batch_op.alter_column('agent_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"),
               server_default=None)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('total_token_count')
        batch_op.drop_column('conversation_count')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
