#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //新增 agent.heartbeat_at
* @File: a91c4e7b2d18_新增_agent_heartbeat_at.py
* @Time: 2026/10/07 16:36:00
* @All Rights Reserve By Brtc
'''
"""新增 agent.heartbeat_at

Revision ID: a91c4e7b2d18
Revises: e8b4c1d07a26
Create Date: 2026-10-07 16:36:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91c4e7b2d18'
down_revision = 'e8b4c1d07a26'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，为 agent 表新增 heartbeat_at
    * @Date :2026/10/07 16:36:00
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 agent.heartbeat_at
    * @Date :2026/10/07 16:36:00
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('heartbeat_at')

    # ### end Alembic commands ###
