#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //网关配置下沉到 server，agent 改为 gateway_id 关联
* @File: b7e2a9c04d15_网关配置下沉到_server.py
* @Time: 2026/09/30 05:22:10
* @All Rights Reserve By Brtc
'''
"""网关配置下沉到 server，agent 改为 gateway_id 关联

Revision ID: b7e2a9c04d15
Revises: c1d7a4e82f60
Create Date: 2026-09-30 05:22:10.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b7e2a9c04d15'
down_revision = 'c1d7a4e82f60'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，网关地址与密钥下沉到 server，agent 仅保留 gateway_id
    * @Date :2026/09/30 05:22:10
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.alter_column(
            'url',
            new_column_name='gateway_url',
            existing_type=sa.String(length=255),
            existing_nullable=False,
            existing_server_default=sa.text("''::character varying"),
        )
        batch_op.add_column(sa.Column(
            'gateway_key',
            sa.String(length=255),
            server_default=sa.text("''::character varying"),
            nullable=False,
        ))

    op.execute(sa.text(
        "UPDATE server SET gateway_key = COALESCE(info->>'jwt_key', '')"
    ))
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_column('info')

    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_id', sa.UUID(), nullable=True))

    result = op.get_bind().execute(sa.text(
        "WITH updated AS ("
        "UPDATE agent "
        "SET gateway_id = (SELECT id FROM server ORDER BY updated_at DESC LIMIT 1) "
        "WHERE gateway_id IS NULL "
        "RETURNING id"
        ") SELECT count(*) AS updated_rows FROM updated"
    ))
    updated_rows = result.scalar()
    print(f"回填 agent.gateway_id 更新行数: {updated_rows}")

    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_agent_gateway_id', 'server', ['gateway_id'], ['id'])
        batch_op.drop_column('gateway_url')
        batch_op.drop_column('gateway_key')

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，恢复 agent 网关字段与 server.url、info
    * @Date :2026/09/30 05:22:10
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'gateway_url',
            sa.String(length=255),
            server_default=sa.text("''::character varying"),
            nullable=False,
        ))
        batch_op.add_column(sa.Column(
            'gateway_key',
            sa.String(length=255),
            server_default=sa.text("''::character varying"),
            nullable=False,
        ))

    op.execute(sa.text(
        "UPDATE agent AS a "
        "SET gateway_url = COALESCE(s.gateway_url, ''), "
        "gateway_key = COALESCE(s.gateway_key, '') "
        "FROM server AS s "
        "WHERE a.gateway_id = s.id"
    ))
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_gateway_id', type_='foreignkey')
        batch_op.drop_column('gateway_id')

    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'info',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ))

    op.execute(sa.text(
        "UPDATE server SET info = jsonb_build_object('jwt_key', COALESCE(gateway_key, ''))"
    ))
    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.alter_column(
            'gateway_url',
            new_column_name='url',
            existing_type=sa.String(length=255),
            existing_nullable=False,
            existing_server_default=sa.text("''::character varying"),
        )
        batch_op.drop_column('gateway_key')

    # ### end Alembic commands ###
