#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //conversation 改为 agent_id 外键，删除 peer_id 与 bot_id
* @File: c1d7a4e82f60_conversation_改为_agent_id_外键.py
* @Time: 2026/09/30 01:24:12
* @All Rights Reserve By Brtc
'''
"""conversation 改为 agent_id 外键

Revision ID: c1d7a4e82f60
Revises: f6b2d8a14c37
Create Date: 2026-09-30 01:24:12.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d7a4e82f60'
down_revision = 'f6b2d8a14c37'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，为 conversation 增加 agent_id 外键并删除 peer_id、bot_id
    * @Date :2026/09/30 01:24:12
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.UUID(), nullable=True))

    op.execute(sa.text(
        "UPDATE conversation AS c "
        "SET agent_id = a.id "
        "FROM agent AS a "
        "WHERE c.bot_id = a.bot_id"
    ))
    # 原 bot_id=herms-test-202606-1 已无对应智能体，按旧归属归到觅食小狗
    op.execute(sa.text(
        "UPDATE conversation "
        "SET agent_id = ("
        "SELECT id FROM agent WHERE name = '觅食小狗' AND bot_id = 'herms-test-202606'"
        ") "
        "WHERE title IN ('周末徒步路线', '报销单整理') "
        "AND bot_id = 'herms-test-202606-1'"
    ))
    op.execute(sa.text("ALTER TABLE conversation ALTER COLUMN agent_id SET NOT NULL"))
    op.execute(sa.text(
        "ALTER TABLE conversation ADD CONSTRAINT fk_conversation_agent_id "
        "FOREIGN KEY (agent_id) REFERENCES agent (id)"
    ))
    op.create_index('conversation_agent_id_idx', 'conversation', ['agent_id'], unique=False)
    op.drop_index('conversation_bot_id_idx', table_name='conversation')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('peer_id')
        batch_op.drop_column('bot_id')

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，恢复 conversation.peer_id、bot_id 并删除 agent_id
    * @Date :2026/09/30 01:24:12
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peer_id', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))
        batch_op.add_column(sa.Column('bot_id', sa.String(length=255), nullable=True))

    op.execute(sa.text(
        "UPDATE conversation AS c "
        "SET bot_id = a.bot_id, peer_id = a.peer_id "
        "FROM agent AS a "
        "WHERE c.agent_id = a.id"
    ))
    op.execute(sa.text("ALTER TABLE conversation ALTER COLUMN peer_id SET NOT NULL"))
    op.execute(sa.text("ALTER TABLE conversation ALTER COLUMN bot_id SET NOT NULL"))
    op.execute(sa.text("ALTER TABLE conversation DROP CONSTRAINT fk_conversation_agent_id"))
    op.drop_index('conversation_agent_id_idx', table_name='conversation')
    op.create_index('conversation_bot_id_idx', 'conversation', ['bot_id'], unique=False)
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###
