#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //新增 agent.gateway_key
* @File: c8f1a4e92b07_新增_agent_gateway_key.py
* @Time: 2026/09/29 21:01:17
* @All Rights Reserve By Brtc
'''
"""新增 agent.gateway_key

Revision ID: c8f1a4e92b07
Revises: e383319a1544
Create Date: 2026-09-29 21:01:17.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f1a4e92b07'
down_revision = 'e383319a1544'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，为 agent 表新增 gateway_key
    * @Date :2026/09/29 21:01:17
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_key', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 agent.gateway_key
    * @Date :2026/09/29 21:01:17
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('gateway_key')

    # ### end Alembic commands ###
