#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //message 补齐对端消息 ID、状态、推理、扩展信息，并加会话内唯一约束
* @File: d5a91c7e2b48_message_补齐幂等字段与唯一约束.py
* @Time: 2026/09/30 21:02:30
* @All Rights Reserve By Brtc
'''
"""message 补齐幂等字段与唯一约束

Revision ID: d5a91c7e2b48
Revises: b7e2a9c04d15
Create Date: 2026-09-30 21:02:30.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd5a91c7e2b48'
down_revision = 'b7e2a9c04d15'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，为 message 增加幂等写入所需字段和唯一约束
    * @Date :2026/09/30 21:02:30
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'message_id',
            sa.String(length=64),
            server_default=sa.text("''::character varying"),
            nullable=False,
        ))
        batch_op.add_column(sa.Column(
            'message_status',
            sa.SmallInteger(),
            server_default=sa.text('1'),
            nullable=False,
        ))
        batch_op.add_column(sa.Column(
            'message_reasoning',
            sa.Text(),
            server_default=sa.text("''::text"),
            nullable=False,
        ))
        batch_op.add_column(sa.Column(
            'message_info',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ))
        batch_op.create_unique_constraint(
            'uk_message_conversation_message_id',
            ['conversation_id', 'message_id'],
        )

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，去掉 message 的幂等字段和唯一约束
    * @Date :2026/09/30 21:02:30
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('uk_message_conversation_message_id', type_='unique')
        batch_op.drop_column('message_info')
        batch_op.drop_column('message_reasoning')
        batch_op.drop_column('message_status')
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###
