#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //新增 message 表
* @File: e383319a1544_新增_message_表.py
* @Time: 2026/09/23 22:37:05
* @All Rights Reserve By Brtc
'''
"""新增 message 表

Revision ID: e383319a1544
Revises: 306fd0e6f4e4
Create Date: 2026-09-23 22:37:05.105749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e383319a1544'
down_revision = '306fd0e6f4e4'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，创建 message 表
    * @Date :2026/09/23 22:37:05
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('message_role', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('message_content', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('message_token', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('message_latency', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_message_id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('message_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('message_conversation_id_idx', ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 message 表
    * @Date :2026/09/23 22:37:05
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('message_conversation_id_idx')
        batch_op.drop_index('message_account_id_idx')

    op.drop_table('message')
    # ### end Alembic commands ###
