#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //将 agent_id 重命名为 bot_id
* @File: e6a19c4d8b20_重命名_agent_id_为_bot_id.py
* @Time: 2026/09/20 23:31:40
* @All Rights Reserve By Brtc
'''
"""将 agent_id 重命名为 bot_id

Revision ID: e6a19c4d8b20
Revises: 3c5834073468
Create Date: 2026-09-20 23:31:40.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a19c4d8b20'
down_revision = '3c5834073468'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，将 agent.agent_id、conversation.agent_id 重命名为 bot_id，并同步重命名唯一约束与索引
    * @Date :2026/09/20 23:31:40
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.alter_column('agent_id', new_column_name='bot_id')
    op.execute(sa.text("ALTER TABLE agent RENAME CONSTRAINT uk_agent_agent_id TO uk_agent_bot_id"))
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('agent_id', new_column_name='bot_id')
    op.execute(sa.text("ALTER INDEX conversation_agent_id_idx RENAME TO conversation_bot_id_idx"))

    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，将 bot_id 恢复为 agent_id，并同步恢复唯一约束与索引名
    * @Date :2026/09/20 23:31:40
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("ALTER INDEX conversation_bot_id_idx RENAME TO conversation_agent_id_idx"))
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('bot_id', new_column_name='agent_id')
    op.execute(sa.text("ALTER TABLE agent RENAME CONSTRAINT uk_agent_bot_id TO uk_agent_agent_id"))
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.alter_column('bot_id', new_column_name='agent_id')

    # ### end Alembic commands ###
