#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //message 增加写入序号 seq，按插入顺序生成
* @File: e8b4c1d07a26_message_增加写入序号_seq.py
* @Time: 2026/09/30 21:20:40
* @All Rights Reserve By Brtc
'''
"""message 增加写入序号 seq

Revision ID: e8b4c1d07a26
Revises: d5a91c7e2b48
Create Date: 2026-09-30 21:20:40.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b4c1d07a26'
down_revision = 'd5a91c7e2b48'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，为 message 增加单调序号并按原有顺序回填
    * @Date :2026/09/30 21:20:40
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('seq', sa.BigInteger(), nullable=True))
    # 已有行按 (created_at, id) 回填；空表时更新 0 行。不能靠 ADD IDENTITY 自动填，那会按堆顺序。
    result = op.get_bind().execute(sa.text(
        "WITH ordered AS ("
        "SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn "
        "FROM message"
        ") "
        "UPDATE message AS m SET seq = ordered.rn "
        "FROM ordered WHERE m.id = ordered.id"
    ))
    print(f"回填 message.seq 行数: {result.rowcount}")
    op.execute(sa.text("ALTER TABLE message ALTER COLUMN seq SET NOT NULL"))
    op.execute(sa.text(
        "ALTER TABLE message ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY"
    ))
    # 空表时下一值从 1 开始；已有数据时从 max(seq) 之后继续
    op.execute(sa.text(
        "SELECT setval("
        "pg_get_serial_sequence('message', 'seq'), "
        "GREATEST(COALESCE((SELECT MAX(seq) FROM message), 1), 1), "
        "EXISTS (SELECT 1 FROM message))"
    ))
    op.create_index(
        'message_conversation_seq_idx',
        'message',
        ['conversation_id', 'seq'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，去掉 message 的写入序号
    * @Date :2026/09/30 21:20:40
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('message_conversation_seq_idx', table_name='message')
    op.drop_column('message', 'seq')
    # ### end Alembic commands ###
