#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
* This is the projet for brtc R&D Platform
* @Author Leon-liao <liaosiliang1234@126.com>
* @Description //新增 conversation.ws_session_id
* @File: f6b2d8a14c37_新增_conversation_ws_session_id.py
* @Time: 2026/09/29 23:22:22
* @All Rights Reserve By Brtc
'''
"""新增 conversation.ws_session_id

Revision ID: f6b2d8a14c37
Revises: c8f1a4e92b07
Create Date: 2026-09-29 23:22:22.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b2d8a14c37'
down_revision = 'c8f1a4e92b07'
branch_labels = None
depends_on = None


def upgrade():
    """
    * @Author Leon-liao
    * @Function:
    upgrade()
    * @Description //升级数据库，为 conversation 表新增 ws_session_id 并回填现存数据
    * @Date :2026/09/29 23:22:22
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ws_session_id', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))

    op.execute("UPDATE conversation SET ws_session_id = peer_id || '-' || left(thread_id, 8)")
    # ### end Alembic commands ###


def downgrade():
    """
    * @Author Leon-liao
    * @Function:
    downgrade()
    * @Description //回滚数据库，删除 conversation.ws_session_id
    * @Date :2026/09/29 23:22:22
    * @Param:
    无
    * @return：无
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('ws_session_id')

    # ### end Alembic commands ###
